COLLECTION_NAME = "documents"

QDRANT_HOST = "localhost"
QDRANT_PORT = 6333

EMBED_MODEL = "nomic-embed-text"

CHUNK_SIZE = 500
CHUNK_OVERLAP = 80

TABLE_ROWS_PRIMARY = 5
TABLE_ROWS_FALLBACK = 1